
Sub CATMain()

Dim iFilter(0)
iFilter(0) = "HybridBody"

Set oSel = CATIA.ActiveDocument.Selection
Rem oSel.Clear
' 定义选择------------------ MsgBox "选择用于提取点的几何集"
UserSelection = oSel.SelectElement2(EnableSelectionFor, "请选择你的点所在几何图形集合", False)
' 评估选择是否正确 -----------------------
	If UserSelection <> "Normal" Then
		MsgBox "几何集选择错误"
		Exit Sub
	Else
	Set ohybridbody = oSel.item(1).Value
	MsgBox "选择的几何集是 : " & ohybridbody.Name
End If


Dim part1 As Part
Set part1 = CATIA.ActiveDocument.Part

Dim axisSystems1 As AxisSystems
Set axisSystems1 = part1.AxisSystems

Dim axisSystem1 As AxisSystem
Set axisSystem1 = axisSystems1.item("axl")






ReDim acoord(2)
 Dim xlApp As Object
    Set xlApp = CreateObject("EXCEL.Application")
    Dim wb As Object
    Set wb = xlApp.Workbooks.Add
	Set ws = wb.ActiveSheet
		

ws.Cells(1, 1).Value = "从CATIA到ws的点提取"
ws.Cells(3, 1).Value = "点的几何集是 : " & ohybridbody.Name
ws.Cells(5, 1).Value = "点名称"
ws.Cells(5, 2).Value = "X"
ws.Cells(5, 3).Value = "Y"
ws.Cells(5, 4).Value = "Z"

Dim i As Integer
Dim iRow As Integer

iRow = 7
Set oshapes = ohybridbody.HybridShapes
For i = 1 To oshapes.Count
oshapes.item(i).GetCoordinates acoord
Set reference1 = oshapes.item(i)
ws.Cells(iRow, 1).Value = reference1.Name
ws.Cells(iRow, 2).Value = acoord(0)
ws.Cells(iRow, 3).Value = acoord(1)
ws.Cells(iRow, 4).Value = acoord(2)
iRow = iRow + 1
Next

MsgBox "处理完成"
End Sub