Sub MeasureElements()


    Dim drawDoc As DrawingDocument
    Set drawDoc = CATIA.ActiveDocument
    
    Dim drawSheet As DrawingSheet
    Set drawSheet = drawDoc.Sheets.ActiveSheet
    
    Dim drawView As DrawingView
    Set drawView = drawSheet.Views.activeView
    
    Dim geoElements As GeometricElements
    Set geoElements = drawView.GeometricElements
    
    Dim geoElement As GeometricElement
    
    
    
'    For Each geoElement In geoElements
'
'
'        Debug.Print TypeName(geoElement)
'
'
'
'    Next geoElement
'
'
'
'    Debug.Print geoElements.Count
    
    
    
    
    Dim sel1 As Selection
    Set sel1 = drawDoc.Selection
    
    sel1.Add drawView
    
    sel1.Search "Name=GeneratedItem,sel"
    
    
    
    
    For i = 1 To sel1.Count2
    
        Debug.Print TypeName(sel1.Item2(i).Value)
        
    Next i
    
    

End Sub